# Generated by Django 2.2.6 on 2021-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('year_in_school', models.CharField(choices=[('Высшее', 'Высшее'), ('Средне-специальное', 'Средне-специальное'), ('Среднее', 'Среднее')], max_length=20)),
                ('dob', models.DateField()),
            ],
        ),
    ]
