# Generated by Django 3.2.8 on 2021-11-06 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20211031_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_accepted',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
