# Generated by Django 3.2.8 on 2021-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_employee_date_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='years_worked',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
